# fly.toml app configuration file generated for mona-late-tree-7299 on 2026-03-24T07:04:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mona-late-tree-7299'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATABASE_PATH = '/data/mona.db'

[[mounts]]
  source = 'mona_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
